# -*- coding: utf-8 -*-
"""DCBD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rVtoOff--4oezxPfuA7te1XBLH0l7t-r

# Name : Sourit Mitra
# Roll : MDS202537
"""

# Step 1 : Installing And Importing

import requests
import time
from multiprocessing import Pool, cpu_count
from collections import Counter

# Step 2 : Adding Configuration

BASE_URL = "http://72.60.221.150:8080"
STUDENT_ID = "MDS202537"

# Step 3 : Login Function

def get_secret_key(student_id):
    url = BASE_URL + "/login"
    response = requests.post(url, json={"student_id": student_id})
    return response.json()["secret_key"]

# Step 4 : Get Master Secret Key

MASTER_SECRET_KEY = get_secret_key(STUDENT_ID)
print(f"Master secret key : {MASTER_SECRET_KEY[:20]}")

# Step 5 : Fetch Title Function

def fetch_title(secret_key, filename, max_retries=3):
    url = BASE_URL + "/lookup"
    payload = {
          "secret_key": secret_key,
        "filename": filename
    }

    for attempt in range(max_retries):
        try:
            res = requests.post(url, json=payload, timeout=10)

            if res.status_code == 200:
                return res.json()["title"]

            elif res.status_code == 429:
                # Exponential backoff
                wait_time = 0.5 * (2 ** attempt)
                time.sleep(wait_time)

            else:
                # For any other error, return None
                return None

        except requests.exceptions.RequestException:
            if attempt == max_retries - 1:
                return None
            time.sleep(1)

    return None

# Step 6 : First Word Extractor

def get_first_word(title):
    if not title:
        return None
    return title.split()[0]

# Step 7: Map Function

def mapper(file_chunk):
    # Use the global MASTER_SECRET_KEY instead of getting a new one
    counter = Counter()

    for filename in file_chunk:
        title = fetch_title(MASTER_SECRET_KEY, filename)
        word = get_first_word(title)

        if word:
            counter[word] += 1

        # Small delay to avoid rate limiting
        time.sleep(0.05)

    return counter

# Step 8 : Creating the file list

print("Testing first 5 files:")
for i in range(5):
    title = fetch_title(MASTER_SECRET_KEY, f"pub_{i}.txt")
    print(f"pub_{i}.txt: {title} -> first word: {get_first_word(title)}")
print("-" * 50)

# Step 9 : Split Work

def chunkify(lst, n):
    return [lst[i::n] for i in range(n)]

# Step 10 : Creating file list

# Create file list
files = [f"pub_{i}.txt" for i in range(1000)]
print(f"Created {len(files)} files")
print(f"First 5 files: {files[:5]}")

# Step 11 : Run Multiprocessing

num_workers = min(cpu_count(), 4)  # Use fewer workers to avoid rate limiting
chunks = chunkify(files, num_workers)

print(f"Using {num_workers} workers...")
print(f"Processing {len(files)} files...")

with Pool(num_workers) as pool:
    results = pool.map(mapper, chunks)

print("Mapping completed.")

# Step 12 : reduce

# Step 10: Reduce
final_counter = Counter()

for c in results:
    final_counter.update(c)

# Check if we got data
total_words = sum(final_counter.values())
print(f"Total words processed: {total_words}")
print(f"Unique words: {len(final_counter)}")
print(f"Top 20 counts: {final_counter.most_common(20)}")

# Step 13 : Top 10

top_10 = [word for word, _ in final_counter.most_common(10)]
print(top_10)

# Step 14 : Verificarion

def verify(top_10):
    secret_key = get_secret_key(STUDENT_ID)

    url = BASE_URL + "/verify"
    payload = {
        "secret_key": secret_key,
        "top_10": top_10
    }

    res = requests.post(url, json=payload)
    print(res.json())

verify(top_10)